/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#eeefff",
        "outline-variant": "#c3c6d7",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "on-background": "#191b23",
        "background": "#faf8ff",
        "surface-container-high": "#e7e7f3",
        "on-primary": "#ffffff",
        "on-surface": "#191b23",
        "tertiary-fixed-dim": "#ffb596",
        "primary": "#004ac6",
        "on-surface-variant": "#434655",
        "secondary": "#505f76",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf8ff",
        "secondary-container": "#d0e1fb",
        "on-primary-fixed": "#00174b",
        "inverse-surface": "#2e3039",
        "tertiary": "#943700",
        "on-primary-fixed-variant": "#003ea8",
        "surface-dim": "#d9d9e5",
        "surface-container-low": "#f3f3fe",
        "surface-container": "#ededf9",
        "secondary-fixed-dim": "#b7c8e1",
        "error": "#ba1a1a",
        "surface-container-highest": "#e1e2ed",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-container": "#ffede6",
        "primary-fixed": "#dbe1ff",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed-dim": "#b4c5ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#54647a",
        "primary-container": "#2563eb",
        "surface-tint": "#0053db",
        "outline": "#737686",
        "on-secondary-fixed-variant": "#38485d",
        "surface-variant": "#e1e2ed",
        "on-error-container": "#93000a",
        "tertiary-container": "#bc4800",
        "surface": "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed": "#ffdbcd"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin": "32px",
        "xl": "32px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "base": "8px",
        "lg": "24px",
        "gutter": "24px",
        "2xl": "48px"
      },
      "fontFamily": {
        "inter": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-base": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h3": ["20px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
